matrix:
  include:
    - os: linux
      dist: xenial
      language: android
      sudo: false
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
            - sshpass
      before_script:
        - export LANG=en_US.UTF-8
        - mkdir -p $HOME/.download
        - if test ! -e $DOWNLOAD_PATH/sdk-tools.zip ; then wget $ANDROID_SDK_URL -P $DOWNLOAD_PATH && mv $DOWNLOAD_PATH/sdk-tools*.zip $DOWNLOAD_PATH/sdk-tools.zip ; fi
        - if test ! -e $DOWNLOAD_PATH/gradle-4.10-all.zip ; then wget $GRADLE_URL -P $DOWNLOAD_PATH ; fi
        - unzip -qq $DOWNLOAD_PATH/sdk-tools.zip -d $ANDROID_HOME
        - unzip -qq $DOWNLOAD_PATH/gradle-4.10-all.zip -d $HOME
        - git clone -b dev $FLUTTER_GIT $FLUTTER_PATH
        - export PATH="$GRADLE_HOME/bin:$PATH:$GRADLE_HOME/bin:$ANDROID_HOME/tools/bin:$HOME/flutter/bin"
        - if test ! -e $HOME/.android/repositories.cfg ; then touch $HOME/.android/repositories.cfg ; fi
        - echo y | sdkmanager 'tools' > /dev/null
        - echo y | sdkmanager 'platform-tools' > /dev/null
        - echo y | sdkmanager 'build-tools;28.0.3' > /dev/null
        - echo y | sdkmanager 'platforms;android-27' > /dev/null
        - echo y | sdkmanager 'extras;google;m2repository' > /dev/null
      script:
        - gradle -v
        - sdkmanager --licenses
        - flutter doctor --android-licenses
        - flutter doctor -v
        - flutter precache
        - flutter build -v build apk
        # - ls $DOWNLOAD_PATH
        # - ls $ANDROID_HOME
        # - ls $FLUTTER_PATH
        # - echo $PATH
        # - ls $GRADLE_HOME
        # - gradle -v
        # - $GRADLE_HOME/bin/gradle -v
cache:
  directories:
    - $HOME/.android
    - $HOME/.download
    - $HOME/.pub-cache
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
    - /var/cache/oracle-jdk8-installer
env:
  global:
    - GRADLE_URL=https://services.gradle.org/distributions/gradle-4.10-all.zip
    - ANDROID_SDK_URL=https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    - FLUTTER_GIT=https://github.com/flutter/flutter.git
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - FLUTTER_PATH=$HOME/flutter
    - ANDROID_HOME=$HOME/android-sdk
    - DOWNLOAD_PATH=$HOME/.download
    - GRADLE_HOME=$HOME/gradle-4.10