matrix:
  include:
    - os: linux
      dist: xenial
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
      before_script:
        - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
        - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk
        - echo yes | $HOME/android-sdk/tools/bin/sdkmanager 'tools' > /dev/null
        - echo yes | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools' > /dev/null
        - echo yes | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;27.0.3' > /dev/null
        - echo yes | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-27' > /dev/null
        - echo yes | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository' > /dev/null

        - wget https://services.gradle.org/distributions/gradle-4.1-all.zip
        - unzip -o -qq gradle-4.1-all.zip
        - export GRADLE_HOME=$PWD/gradle-4.1
        - export PATH=$GRADLE_HOME/bin:$PATH
        - mkdir -p flutter
        - cd flutter
        - wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.0.0-stable.tar.xz
        - tar xf flutter_linux_v1.0.0-stable.tar.xz
        - export PATH="$PATH:`pwd`/flutter/bin"
        - cd ..
      script:
        - echo yes | sdkmanager --licenses
        - flutter config --no-analytics
        - flutter channel beta
        - flutter upgrade
        - flutter doctor
cache:
  directories:
    - $HOME/android-sdk-dl
    - $HOME/android-sdk
    - $HOME/.pub-cache
    - $PWD/flutter
    - $PWD/gradle-4.1
env:
  - ANDROID_HOME=$HOME/android-sdk