matrix:
  include:
    - os: linux
      dist: xenial
      language: android
      sudo: false
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
            - sshpass
      before_script:
        - export LANG=en_US.UTF-8
        - mkdir -p $HOME/.download
        - if test ! -e $DOWNLOAD_PATH/sdk-tools.zip ; then wget $ANDROID_SDK_URL -P $DOWNLOAD_PATH && mv $DOWNLOAD_PATH/sdk-tools*.zip $DOWNLOAD_PATH/sdk-tools.zip ; fi
        - if test ! -e $DOWNLOAD_PATH/gradle-4.1-all.zip ; then wget $GRADLE_URL -P $DOWNLOAD_PATH ; fi
        - unzip -qq $DOWNLOAD_PATH/sdk-tools.zip -d $ANDROID_HOME
        - unzip -qq $DOWNLOAD_PATH/gradle-4.1-all.zip -d $HOME
        - git clone -b dev $FLUTTER_GIT $FLUTTER_PATH --depth 1
        - export PATH="$GRADLE_HOME/bin:$ANDROID_HOME/tools/bin:$PATH:$GRADLE_HOME/bin:$ANDROID_HOME/tools/bin:$HOME/flutter/bin"
        - if test ! -e $HOME/.android/repositories.cfg ; then touch $HOME/.android/repositories.cfg ; fi
        - echo y | sdkmanager 'tools' > /dev/null
        - echo y | sdkmanager 'platform-tools' > /dev/null
        - echo y | sdkmanager 'build-tools;28.0.3' > /dev/null
        - echo y | sdkmanager 'platforms;android-27' > /dev/null
        - echo y | sdkmanager 'extras;google;m2repository' > /dev/null
      script:
        - echo -y | sdkmanager --licenses
        - echo -y | flutter doctor -v > /dev/null
        - flutter update-packages
        - flutter precache
        - flutter -v build apk

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.android
    - $HOME/.download
    - $HOME/.pub-cache
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
env:
  global:
    - GRADLE_URL=https://services.gradle.org/distributions/gradle-4.1-all.zip
    - ANDROID_SDK_URL=https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    - FLUTTER_GIT=https://github.com/flutter/flutter.git
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - FLUTTER_PATH=$HOME/flutter
    - ANDROID_HOME=$HOME/android-sdk
    - DOWNLOAD_PATH=$HOME/.download
    - GRADLE_HOME=$HOME/gradle-4.1
before_deploy:
  - git config --local user.name idnesdotlink
  - git config --local user.email 16096613+idnesdotlink@users.noreply.github.com
  - export TRAVIS_TAG=${TRAVIS_TAG:$(git log --format=%h -1)}
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: "PUT/0qrm2+lDQpnf5jtRlfKOKMwBIPA+Bq8+jjE2VonMye7Z4FMWwETg7XA6TwCnMA5vp8v27EtfwzcPSnVKRzJIMlxJbjJsW0JzfYK+rbrZxvVFBHRdDnAqvtfzg2h046rlFuIeBNcvI0qny8S81TtPfn6SpPQ/A0ILggOaJG87MfVFk2mGmJZbdzb5LLSawqpLFurboTECEbM2wIJ2+NWsOxSTQWbbfpTVpQ6NbW3WhOzZXp9YOB9lXT9HlACjLQyyZpFvzy0xPl9hjhfL8GYKzPq64btrSlcZLQxBxuXP9nSTMRoH/KwSHzKuIYS951EkLXutQoa9BfSigrTb1O/s8ENXrd5lG7h3gIWZxR9hJmcbTwF05u/SXU0+kTTmYkyQyuX1XMeyikPR558E7/OqUcFDIbBjusdfN7AQqyT+aXXFJIHkNzHz1BvVUuRxn04c2S/VoxXXGxDx1a3REQOBreTClp9oZuGQXBQ5qpxDyAP0rkhHVNTRW1ruB7XsCFNppfKcVDcXyVNN178xfm8bc7w4DJbDyxjT5meHwWAZW+CQOlEMMvH+4gcgmSr68C3iUKpDUprGCDKoRyns9w00ALl/3kqjh55GO3bbzqtqQBvDK3mD1TIfPKVP3KwVpmq8HioHL5e0PFU0GyZNqw3fZf8j3Nwn5XmH6YrQfc0="
  file: $HOME/build/app/outputs/apk/release/app-release.apk
  skip_cleanup: true
  on:
    tags: true