matrix:
  include:
    - os: linux
      dist: xenial
      language: android
      sudo: false
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
            - sshpass
      before_script:
        - export LANG=en_US.UTF-8
        - curl -s get.sdkman.io | bash
        - source "$HOME/.sdkman/bin/sdkman-init.sh"
        - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
        - source "/home/travis/.sdkman/bin/sdkman-init.sh"
        - sdk install gradle 4.1
        - sdk default gradle 4.1
        - mkdir -p $HOME/.download
        - if test ! -e $DOWNLOAD_PATH/sdk-tools.zip ; then wget $ANDROID_SDK_URL -P $DOWNLOAD_PATH && mv $DOWNLOAD_PATH/sdk-tools*.zip $DOWNLOAD_PATH/sdk-tools.zip ; fi
        - unzip -qq $DOWNLOAD_PATH/sdk-tools.zip -d $ANDROID_HOME
        - git clone -b dev $FLUTTER_GIT $FLUTTER_PATH
        - export PATH="$PATH:$ANDROID_HOME/tools/bin:$HOME/flutter/bin"
        - echo y | sdkmanager 'tools' > /dev/null
        - echo y | sdkmanager 'platform-tools' > /dev/null
        - echo y | sdkmanager 'build-tools;28.0.3' > /dev/null
        - echo y | sdkmanager 'platforms;android-27' > /dev/null
        - echo y | sdkmanager 'extras;google;m2repository' > /dev/null
      script:
        - ls $DOWNLOAD_PATH
        - ls $ANDROID_HOME
        - ls $FLUTTER_PATH
        - echo $PATH
        - gradle -v
        - flutter -v
cache:
  directories:
    - $HOME/.download
    - $HOME/.pub-cache
    # - $HOME/.gradle/caches
    # - $HOME/.gradle/wrapper
env:
  global:
    - ANDROID_SDK_URL=https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    - FLUTTER_GIT=https://github.com/flutter/flutter.git
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - FLUTTER_PATH=$HOME/flutter
    - ANDROID_HOME=$HOME/android-sdk
    - DOWNLOAD_PATH=$HOME/.download