matrix:
  include:
    - os: linux
      dist: xenial
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-25.0.3
          - android-25
          - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      sudo: false
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - oracle-java8-installer
            - oracle-java8-set-default
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
            - sshpass
      before_script:
        - export LANG=en_US.UTF-8
        - mkdir -p $HOME/.download
        - if test ! -e $DOWNLOAD_PATH/sdk-tools.zip ; then wget $ANDROID_SDK_URL -P $DOWNLOAD_PATH && mv $DOWNLOAD_PATH/sdk-tools*.zip $DOWNLOAD_PATH/sdk-tools.zip ; fi
        - if test ! -e $DOWNLOAD_PATH/gradle-4.1-all.zip ; then wget $GRADLE_URL -P $DOWNLOAD_PATH ; fi
        - unzip -qq $DOWNLOAD_PATH/gradle-4.1-all.zip -d $GRADLE_HOME
        - unzip -qq $DOWNLOAD_PATH/sdk-tools.zip -d $ANDROID_HOME
        - git clone -b dev $FLUTTER_GIT $FLUTTER_PATH
      script:
        - ls $DOWNLOAD_PATH
        - ls $ANDROID_HOME
        - ls $GRADLE_HOME
        - ls $FLUTTER_PATH
cache:
  directories:
    - $HOME/.download
    - $HOME/.pub-cache
env:
  global:
    - ANDROID_SDK_URL=https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    - GRADLE_URL=https://services.gradle.org/distributions/gradle-4.1-all.zip
    - FLUTTER_GIT=https://github.com/flutter/flutter.git
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - GRADLE_HOME=$HOME/gradle-4.1
    - FLUTTER_PATH=$HOME/flutter
    - ANDROID_HOME=$HOME/android-sdk
    - DOWNLOAD_PATH=$HOME/.download