matrix:
  include:
    - os: linux
      dist: xenial
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-25.0.3
          - android-25
          - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
      before_script:
        # wget resource and keep in cache
        - wget $GRADLE_URL -P $DOWNLOAD_PATH
        - wget $FLUTTER_URL -P $DOWNLOAD_PATH
      script:
        - ls $DOWNLOAD_PATH
cache:
  directories:
    - $HOME/.download
    - $HOME/.pub-cache
env:
  global:
    - GRADLE_URL=https://services.gradle.org/distributions/gradle-4.1-all.zip
    - FLUTTER_URL=https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.0.0-stable.tar.xz
    - GRADLE_HOME=$HOME/gradle-4.1
    - FLUTTER_PATH=$HOME/flutter
    - DOWNLOAD_PATH=$HOME/.download