matrix:
  include:
    - os: linux
      dist: xenial
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools-26.1.1
          - platform-tools-28.0.1
          - build-tools-28.0.3
          - android-25
          - sys-img-armeabi-v7a-google_apis-25
          - extra-google-google_play_services
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
            - libglu1-mesa
            - libglu1-mesa-dev
            - unzip
            - xz-utils
      before_script:
        - wget https://services.gradle.org/distributions/gradle-4.1-all.zip
        - unzip -qq gradle-4.1-all.zip
        - export GRADLE_HOME=$PWD/gradle-4.1
        - export PATH=$GRADLE_HOME/bin:$PATH
        - mkdir flutter
        - cd flutter
        - wget https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.0.0-stable.tar.xz
        - tar xf flutter_linux_v1.0.0-stable.tar.xz
        - export PATH="$PATH:`pwd`/flutter/bin"
        - cd ..
      script:
        - flutter doctor --android-licenses -y
        - flutter channel beta
        - flutter upgrade
        - flutter doctor
cache:
  directories:
    - $HOME/.pub-cache
    - $PWD/flutter