version: 0.1.{build}

image:
  - Visual Studio 2017

platform:
  - x64

# gradle            = https://services.gradle.org/distributions/gradle-4.1-all.zip
# android-sdk-tools = https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip

init:
  # set environtment
  - cmd: SET ANDROID_DIR="C:\\Android"
  - cmd: SET APPVEYOR_ANDROID="C:\\Users\appveyor\\.android"
  - cmd: SET ANDROID_SDK_ROOT="C:\\Android"
  - cmd: SET ANDROID_TOOLS_DIR=C:\\Android\\tools
  - cmd: SET ANDROID_TOOLS_BIN=C:\\Android\\tools\\bin
  - cmd: SET ANDROID_PLATFORM_TOOLS_DIR=C:\\Android\\platform-tools

  # git config
  - cmd: git config --global core.autocrlf input

  # set flutter
  - cmd: git clone -b dev https://github.com/flutter/flutter.git C:\\flutter --depth 1
  - cmd: SET FLUTTER_PATH="C:\\flutter"

  # set gradle
  - appveyor DownloadFile https://services.gradle.org/distributions/gradle-4.1-all.zip
  - 7z x gradle-4.1-all.zip -oC:\
  - cmd: SET GRADLE_HOME="C:\\gradle-4.1"

  # android-sdk-windows
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\Android

  # add all to path
  - cmd: SET PATH=C:\\gradle-4.1\\bin;C:\\Android\\tools;C:\\Android\\platform-tools;C:\\Android\\tools\\bin;C:\\flutter\\bin;%PATH%
  - cmd: SET PATH=%PATH%;C:\\gradle-4.1\\bin;C:\\Android\\tools;C:\\Android\\platform-tools;C:\\Android\\tools\\bin;C:\\flutter\\bin

  # TODO: find alternative appveyor syntax
  - yes | C:\\Android\tools\bin\sdkmanager.bat tools > nul
  - yes | C:\\Android\tools\bin\sdkmanager.bat platform-tools > nul
  - yes | C:\\Android\tools\bin\sdkmanager.bat build-tools;28.0.3 > nul
  - yes | C:\\Android\tools\bin\sdkmanager.bat platforms;android-27 > nul
  - yes | C:\\Android\tools\bin\sdkmanager.bat extras;google;m2repository > nul

  # TODO: find alternative appveyor syntax
  - yes | C:\\Android\tools\bin\sdkmanager.bat --licenses > nul
  - cmd: ECHO y | flutter doctor -v
  - flutter update-packages
  - flutter precache

build_script:
  - flutter -v build apk

test: off

deploy: off