version: 0.1.{build}

image:
  - Visual Studio 2017

platform:
  - x64

init:
  - cmd: ECHO "START"
  - cmd: git config --global core.autocrlf input
  - cmd: CD
  - cmd: DIR

  - cmd: SET ANDROID_SDK_TOOLS="C:\\Android"
  - cmd: SET APPVEYOR_ANDROID="C:\\Users\appveyor\\.android"
  - cmd: SET ANDROID_SDK_ROOT=%ANDROID_SDK_TOOLS%
  - cmd: SET ANDROID_HOME=%ANDROID_SDK_TOOLS%

  #flutter
  - cmd: git clone -b dev https://github.com/flutter/flutter.git C:\\flutter --depth 1
  - cmd: SET FLUTTER_PATH="C:\\flutter"
  - cmd: CD %FLUTTER_PATH%
  - cmd: DIR

  # gradle
  - appveyor DownloadFile https://services.gradle.org/distributions/gradle-4.1-all.zip
  - 7z x gradle-4.1-all.zip -oC:\
  - cmd: SET GRADLE_HOME="C:\\gradle-4.1"
  - cmd: CD %GRADLE_HOME%
  - cmd: DIR

  # android-sdk-windows
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\Android
  - cmd: CD %ANDROID_SDK_TOOLS%
  - cmd: DIR

  # java
  - cmd: SET JAVA_HOME="C:\\Program Files\\Java\\jdk1.8.0"
  - cmd: CD %JAVA_HOME%
  - cmd: DIR

  # add all to path
  - cmd: SET PATH=%JAVA_HOME%\\bin;%GRADLE_HOME%\\bin;%ANDROID_SDK_TOOLS%\\tools;%ANDROID_SDK_TOOLS%\\platform-tools;%ANDROID_SDK_TOOLS%\\tools\\bin;%FLUTTER_PATH%\\bin;%PATH%%JAVA_HOME%\\bin;%GRADLE_HOME%\\bin;%ANDROID_SDK_TOOLS%\\tools;%ANDROID_SDK_TOOLS%\\platform-tools;%ANDROID_SDK_TOOLS%\\tools\\bin;%FLUTTER_PATH%\\bin

  # - cmd: sdkmanager --help
  - yes | C:\\Android\tools\bin\sdkmanager.bat tools --sdk_root=%ANDROID_SDK_ROOT%
  - yes | C:\\Android\tools\bin\sdkmanager.bat platform-tools --sdk_root=%ANDROID_SDK_ROOT%
  - yes | C:\\Android\tools\bin\sdkmanager.bat build-tools;28.0.3 --sdk_root=%ANDROID_SDK_ROOT%
  - yes | C:\\Android\tools\bin\sdkmanager.bat platforms;android-27 --sdk_root=%ANDROID_SDK_ROOT%
  - yes | C:\\Android\tools\bin\sdkmanager.bat extras;google;m2repository --sdk_root=%ANDROID_SDK_ROOT%

  - cmd: CD %APPVEYOR_ANDROID%
  - cmd: DIR

  - cmd: CD %ANDROID_SDK_TOOLS%
  - cmd: DIR

  # - cmd: sdkmanager --help

  - cmd: CD %APPVEYOR_BUILD_FOLDER%
  - cmd: DIR
  - cmd: ECHO y | sdkmanager --licenses > nul
  - cmd: ECHO y | flutter doctor -v
  # - flutter update-packages
  # - flutter precache

build_script:
  - cmd: ECHO "END"
  # - flutter -v build apk

test: off

deploy: off