version: 0.1.{build}

image:
  - Visual Studio 2017

platform:
  - x64

clone_folder: c:\projects\autodrive
clone_depth: 1

init:
  - cmd: git config --global core.autocrlf input

  #flutter
  - cmd: git clone -b dev https://github.com/flutter/flutter.git C:\\flutter --depth 1
  - cmd: SET FLUTTER_PATH=C:\\flutter
  - cmd: dir %FLUTTER_PATH%

  # gradle
  - appveyor DownloadFile https://services.gradle.org/distributions/gradle-4.1-all.zip
  - 7z x gradle-4.1-all.zip -oC:\
  - cmd: SET GRADLE_HOME=C:\\gradle-4.1
  - cmd: DIR %GRADLE_HOME%

  # android-sdk-windows
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\android-sdk-windows
  - cmd: SET ANDROID_HOME=C:\\android-sdk-windows

  # java
  - cmd: SET JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0
  - cmd: DIR %JAVA_HOME%

  # add all to path
  - cmd: SET PATH=%JAVA_HOME%\\bin;%GRADLE_HOME%\\bin;%ANDROID_HOME%\\tools\\bin;%FLUTTER_PATH%\\bin;%PATH%

  #project_path
  - cmd: SET PROJECT_PATH=C:\\projects
  - cmd: DIR %PROJECT_PATH%

  - cmd: CD
  - cmd: ECHO y | sdkmanager.bat --licenses
  - cmd: ECHO y | flutter doctor -v
  - flutter update-packages
  - flutter precache

build_script:
  - cmd: cd C:\\projects
  - cmd: DIR
  - flutter -v build apk

test: off

deploy: off