name: autodrive
description: autodrive.

dependencies:
  flutter:
    sdk: flutter
  after_layout: 1.0.7
  archive: 2.0.8
  async_loader: 0.1.2
  bloc: 0.9.5
  cached_network_image: 0.7.0
  camera: 0.4.2
  carousel_pro: 0.0.13
  charts_flutter: 0.6.0
  common_utils: 1.1.1
  connectivity: 0.4.2
  date_range_picker: 1.0.5
  device_info: 0.4.0+1
  dio: 2.0.18
  equatable: 0.2.2
  firebase_admob: 0.8.0+3
  firebase_analytics: 2.0.3
  firebase_auth: 0.8.1+4
  firebase_dynamic_links: 0.2.0+3
  firebase_messaging: 4.0.0+1
  flare_flutter: 1.3.2
  fluro: 1.4.0
  flushbar: 1.2.4
  flutter_advanced_networkimage: 0.4.12
  flutter_bloc: 0.7.1
  flutter_cache_manager: 0.3.2
  flutter_calendar_carousel: 1.3.15+3
  flutter_circular_chart: 0.1.0
  flutter_colorpicker: 0.2.1
  flutter_easyrefresh: 1.2.5
  flutter_local_notifications: 0.5.1+2
  flutter_map: 0.4.0
  flutter_markdown: 0.2.0
  flutter_picker: 1.0.8
  flutter_range_slider: 1.1.0
  flutter_sequence_animation: 3.0.1
  flutter_slidable: 0.4.9
  flutter_socket_io: 0.4.6
  flutter_sparkline: 0.1.0
  flutter_speed_dial: 1.1.1
  flutter_spinkit: 3.1.0
  flutter_staggered_grid_view: 0.2.7
  # flutter_statusbar_manager: 1.0.2
  flutter_svg: 0.11.0
  flutter_swiper: 1.1.4
  flutter_villains: 1.2.0
  font_awesome_flutter: 8.4.0
  google_sign_in: 4.0.1+1
  http: 0.12.0+1
  image_picker: 0.5.0+3
  intl: 0.15.7
  intro_views_flutter: 2.4.0
  json_annotation: 2.0.0
  json_serializable: 2.0.2
  material_design_icons_flutter: 3.2.3595
  material_search: 0.2.8
  meta: 1.1.6
  open_file: 1.2.3+1
  open_iconic_flutter: 0.3.0
  path_provider: 0.5.0+1
  percent_indicator: 1.0.14
  photo_view: 0.2.1
  qr_flutter: 2.0.0+51
  qr_reader: 0.1.3
  quick_actions: 0.3.0+1
  rx_command: 4.2.0
  rxdart: 0.20.0
  scoped_model: 1.0.1
  shared_preferences: 0.5.1+1
  simple_auth_flutter: 2.0.4
  sqflite: 1.1.1
  sticky_headers: 0.1.7
  url_launcher: 5.0.1
  validate: 1.7.0
  validators: 1.0.0+1
  web_socket_channel: 1.0.9

  # IOS
  cupertino_icons: 0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # material icon
  uses-material-design: true

  assets:
    # svg
    - assets/svg/autodrive.svg
